### ISSUE TITLE
No component with name...

### ISSUE THREAD

**Issue by UniqASL** [equinor/neqsimpython#105]
Dear Even Solbraa,

I updated neqsim to the last version (2.2.32 --> 2.3.1) and I am now getting an error message while running the following code:

```python
from neqsim.thermo import fluid

gas = {"methane": 95, "nitrogen": 1, "CO2": 0.2, "ethane": 1, "propane": 0.6, "butane": 0.3, "pentane": 0.08, "hexane": 0.4, "O2": 0.05}

for key in gas.keys():
    fluid().addComponent(key, gas[key], "mol/sec")
```

And I get the following messages:

```
No component with name: butane in database
No component with name: pentane in database
No component with name: hexane in database
No component with name: O2 in database
```

This was not the case before the update. Any idea about that?

Thanks for your support.

**Comment by EvenSol** [comment]
Hi.
I think the error is due to the component names. See available compnents in this file:
https://github.com/equinor/neqsim/blob/master/src/main/resources/neqsim_component_names.txt


Try to run the following code:

from neqsim.thermo import fluid,fluid_df,TPflash,printFrame
import pandas as pd

gas = {"methane": 95, "nitrogen": 1, "CO2": 0.2, "ethane": 1, "propane": 0.6, "n-butane": 0.3, "n-pentane": 0.08, "n-hexane": 0.4, "oxygen": 0.05}

fluid = fluid('srk')
for key in gas.keys():
    fluid.addComponent(key, gas[key], "mol/sec")

fluid.setTemperature(320.0, 'K')
fluid.setPressure(10.0, 'bara')
TPflash(fluid)
printFrame(fluid)



#Alternative way of creating fluid
# Create a gas-condensate fluid
naturalgas = {'ComponentName':  ["nitrogen", "CO2", "methane", "ethane", "propane", "i-butane", "n-butane", "i-pentane", "n-pentane", "n-hexane"], 
        'MolarComposition[-]':  [0.34, 0.84, 90.4, 5.199, 2.06, 0.36, 0.55, 0.14, 0.097, 0.014]
} 

naturalgasdf = pd.DataFrame(naturalgas) 
naturalgasFluid = fluid_df(naturalgasdf)

naturalgasFluid.setTemperature(320.0, 'K')
naturalgasFluid.setPressure(10.0, 'bara')
TPflash(naturalgasFluid)
printFrame(naturalgasFluid)

**Comment by UniqASL** [comment]
Thank you very much for the reply. Indeed, I think it was also not correct before, but as I did not get a feedback from neqsim, I did not noticed that something was wrong.

I guess the fact that I am now getting an error message is because of the new Java bridge since v. 2.3.0. Thanks for that, it is useful to get feedback from the tool.

And thanks for the alternative method to create a fluid.
